#include "emit.hpp"

#include <algorithm>
#include <cstdio>
#include <fstream>
#include <stdexcept>
#include <vector>

namespace protogen {

namespace {

struct IdEntry {
    std::string name;  // proto message name
    std::uint32_t id;
};

std::vector<IdEntry> id_entries(const ProtoFile& file) {
    std::vector<IdEntry> entries;
    for (const auto& m : file.messages)
        if (m.id != 0)
            entries.push_back(IdEntry{m.name, m.id});
    std::sort(entries.begin(), entries.end(),
              [](const IdEntry& a, const IdEntry& b) { return a.id < b.id; });
    for (std::size_t i = 1; i < entries.size(); ++i)
        if (entries[i].id == entries[i - 1].id)
            throw std::runtime_error("duplicate message id " + std::to_string(entries[i].id) +
                                     " (" + entries[i - 1].name + " and " + entries[i].name + ")");
    if (entries.empty())
        throw std::runtime_error("no messages carry an (id) option");
    return entries;
}

}  // namespace

void emit_registry(const ProtoFile& file, const std::string& include_dir,
                   const std::string& src_dir) {
    const std::vector<IdEntry> entries = id_entries(file);

    // --- api_registry.cpp ---
    {
        const std::string path = src_dir + "/api_registry.cpp";
        std::ofstream os(path, std::ios::binary | std::ios::trunc);
        if (!os)
            throw std::runtime_error("cannot open " + path);
        os << "// Generated by tools/protogen — do not edit.\n";
        os << "#include <esphome/api/proto/api_messages.hpp>\n\n";
        os << "namespace esphome::api::proto {\n\n";

        os << "std::unique_ptr<ProtoMessage> create_message(std::uint32_t id) {\n";
        os << "    switch (id) {\n";
        for (const auto& [name, id] : entries)
            os << "    case " << id << ": return std::make_unique<" << cpp_ident(name)
               << ">();\n";
        os << "    default: return nullptr;\n";
        os << "    }\n}\n\n";

        os << "bool registry_contains(std::uint32_t id) {\n";
        os << "    switch (id) {\n";
        for (const auto& [name, id] : entries)
            os << "    case " << id << ":\n";
        os << "        return true;\n";
        os << "    default: return false;\n";
        os << "    }\n}\n\n";

        os << "std::size_t registry_size() { return " << entries.size() << "; }\n\n";

        os << "const char* registry_name(std::uint32_t id) {\n";
        os << "    switch (id) {\n";
        for (const auto& [name, id] : entries)
            os << "    case " << id << ": return \"" << name << "\";\n";
        os << "    default: return \"Unknown\";\n";
        os << "    }\n}\n\n";

        os << "}  // namespace esphome::api::proto\n";
    }

    // --- message_id.hpp (same contract as the old gen_message_ids.cpp) ---
    {
        const std::string path = include_dir + "/message_id.hpp";
        std::ofstream os(path, std::ios::binary | std::ios::trunc);
        if (!os)
            throw std::runtime_error("cannot open " + path);
        const std::uint32_t max_id = entries.back().id;

        os << "// Generated by tools/protogen — do not edit.\n";
        os << "#pragma once\n\n";
        os << "#include <cstddef>\n#include <cstdint>\n\n";
        os << "namespace esphome::api {\n\n";
        os << "/// Stable wire identifier for each ESPHome native-API message,\n";
        os << "/// taken from the proto custom option `(id)`.\n";
        os << "enum class MessageId : std::uint32_t {\n";
        os << "    Unknown = 0,\n";
        for (const auto& [name, id] : entries)
            os << "    " << name << " = " << id << ",\n";
        os << "};\n\n";
        os << "/// Number of distinct message ids defined by the protocol.\n";
        os << "inline constexpr std::size_t message_id_count = " << entries.size() << ";\n\n";
        os << "/// Largest message id defined by the protocol.\n";
        os << "inline constexpr std::uint32_t message_id_max = " << max_id << ";\n\n";
        os << "/// Human-readable name for a message id (its proto message name), or\n";
        os << "/// \"Unknown\" for ids the build did not know about.\n";
        os << "inline const char* to_string(MessageId id) {\n";
        os << "    switch (id) {\n";
        for (const auto& [name, id] : entries)
            os << "    case MessageId::" << name << ": return \"" << name << "\";\n";
        os << "    default: return \"Unknown\";\n";
        os << "    }\n";
        os << "}\n\n";
        os << "}  // namespace esphome::api\n";
    }
}

}  // namespace protogen
