#include "emit.hpp"

#include <fstream>
#include <stdexcept>

namespace protogen {

void emit_enums(const ProtoFile& file, const std::string& out_dir) {
    const std::string path = out_dir + "/api_enums.hpp";
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    if (!out)
        throw std::runtime_error("cannot open " + path);

    out << "// Generated by tools/protogen — do not edit.\n";
    out << "#pragma once\n\n";
    out << "#include <cstdint>\n\n";
    out << "namespace esphome::api::proto {\n\n";

    for (const auto& [name, values] : file.enums) {
        out << "enum " << cpp_ident(name) << " : int {\n";
        for (const auto& [n, number] : values)
            out << "    " << cpp_ident(n) << " = " << number << ",\n";
        out << "};\n\n";
    }

    out << "}  // namespace esphome::api::proto\n";
}

}  // namespace protogen
