/// @file
/// @brief protogen — the self-contained build-time code generator for the
///        ESPHome native API.
///
/// Parses the two vendored .proto files directly and emits lightweight message
/// classes, enums, the id<->type registry, and message_id.hpp. The wire codec
/// lives in committed headers (proto/wire.hpp, proto/proto_message.hpp). Output
/// is byte-for-byte identical to the reference proto3 wire format (enforced by
/// the golden test).
///
/// @verbatim
/// Usage: protogen <api.proto> <api_options.proto> <out_dir>
///   <out_dir>/include/esphome/api/proto/{api_enums.hpp, api_messages.hpp,
///                                        message_id.hpp, api.pb.h}
///   <out_dir>/src/{api_messages.cpp, api_registry.cpp}
/// @endverbatim

#include "emit.hpp"
#include "lexer.hpp"
#include "parser.hpp"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>

namespace {

std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in)
        throw std::runtime_error("cannot read " + path);
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

void make_dir(const std::string& path) {
    std::error_code ec;
    std::filesystem::create_directories(path, ec);
    if (ec)
        throw std::runtime_error("cannot create directory " + path + ": " + ec.message());
}

void write_shim(const std::string& include_dir) {
    const std::string path = include_dir + "/api.pb.h";
    std::ofstream os(path, std::ios::binary | std::ios::trunc);
    if (!os)
        throw std::runtime_error("cannot open " + path);
    os << "// Generated by tools/protogen — do not edit.\n";
    os << "// Convenience shim so `#include \"api.pb.h\"` resolves to the generated\n";
    os << "// message + enum headers.\n";
    os << "#pragma once\n\n";
    os << "#include <esphome/api/proto/api_enums.hpp>\n";
    os << "#include <esphome/api/proto/api_messages.hpp>\n";
}

}  // namespace

int main(int argc, char** argv) {
    if (argc != 4) {
        std::fprintf(stderr, "usage: protogen <api.proto> <api_options.proto> <out_dir>\n");
        return 2;
    }
    const std::string api_path = argv[1];
    const std::string options_path = argv[2];
    const std::string out_dir = argv[3];

    const std::string include_dir = out_dir + "/include/esphome/api/proto";
    const std::string src_dir = out_dir + "/src";

    try {
        protogen::ProtoFile file;

        const auto api_tokens = protogen::lex(read_file(api_path), api_path);
        protogen::parse_into(api_tokens, api_path, file);

        const auto opt_tokens = protogen::lex(read_file(options_path), options_path);
        protogen::parse_into(opt_tokens, options_path, file);

        protogen::resolve_types(file);

        make_dir(include_dir);
        make_dir(src_dir);

        protogen::emit_enums(file, include_dir);
        protogen::emit_messages(file, include_dir, src_dir);
        protogen::emit_registry(file, include_dir, src_dir);
        write_shim(include_dir);

        std::fprintf(stderr, "protogen: emitted %zu messages, %zu enums\n", file.messages.size(),
                     file.enums.size());
        return 0;
    } catch (const std::exception& ex) {
        std::fprintf(stderr, "protogen: error: %s\n", ex.what());
        return 1;
    }
}
