// Host build tool: emits include/esphome/api/proto/message_id.hpp by reflecting
// over the generated ESPHome API descriptors and reading each message's custom
// `(id)` option (extension field 1036 on google.protobuf.MessageOptions).
//
// protoc never surfaces `(id)` as a C++ constant, so this tiny tool — linked
// against the same generated descriptors the library uses — recovers the
// mapping at build time. No Python, no runtime reflection in the library's hot
// path (the registry uses reflection, but the strongly-typed enum is static).
//
// Usage: gen_message_ids <out_message_id.hpp>

#include "api.pb.h"
#include "api_options.pb.h"

#include <google/protobuf/descriptor.h>

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

namespace {

struct Entry {
    std::string name;
    std::uint32_t id;
};

} // namespace

int main(const int argc, char** argv) {
    if (argc != 2) {
        std::cerr << "usage: gen_message_ids <out_message_id.hpp>\n";
        return 2;
    }

    const google::protobuf::FileDescriptor* file =
        esphome::api::proto::HelloRequest::descriptor()->file();

    std::vector<Entry> entries;
    entries.reserve(static_cast<std::size_t>(file->message_type_count()));
    for (int i = 0; i < file->message_type_count(); ++i) {
        const google::protobuf::Descriptor* d = file->message_type(i);
        if (const std::uint32_t id = d->options().GetExtension(esphome::api::proto::id); id != 0) {
            entries.push_back(Entry{std::string(d->name()), id});
        }
    }

    std::sort(entries.begin(), entries.end(),
              [](const Entry& a, const Entry& b) { return a.id < b.id; });

    // Reject duplicate ids — they would silently collide in the enum.
    for (std::size_t i = 1; i < entries.size(); ++i) {
        if (entries[i].id == entries[i - 1].id) {
            std::fprintf(stderr, "gen_message_ids: duplicate id %u (%s and %s)\n",
                         entries[i].id, entries[i - 1].name.c_str(), entries[i].name.c_str());
            return 1;
        }
    }
    if (entries.empty()) {
        std::fprintf(stderr, "gen_message_ids: no messages carry an (id) option\n");
        return 1;
    }

    std::ofstream out(argv[1], std::ios::binary | std::ios::trunc);
    if (!out) {
        std::fprintf(stderr, "gen_message_ids: cannot open %s\n", argv[1]);
        return 1;
    }

    const std::uint32_t max_id = entries.back().id;

    out << "// Generated by tools/gen_message_ids.cpp — do not edit.\n";
    out << "#pragma once\n\n";
    out << "#include <cstddef>\n#include <cstdint>\n\n";
    out << "namespace esphome::api {\n\n";
    out << "/// Stable wire identifier for each ESPHome native-API message,\n";
    out << "/// taken from the proto custom option `(id)`.\n";
    out << "enum class MessageId : std::uint32_t {\n";
    out << "    Unknown = 0,\n";
    for (const auto& [name, id] : entries) {
        out << "    " << name << " = " << id << ",\n";
    }
    out << "};\n\n";
    out << "/// Number of distinct message ids defined by the protocol.\n";
    out << "inline constexpr std::size_t message_id_count = " << entries.size() << ";\n\n";
    out << "/// Largest message id defined by the protocol.\n";
    out << "inline constexpr std::uint32_t message_id_max = " << max_id << ";\n\n";
    out << "/// Human-readable name for a message id (its proto message name), or\n";
    out << "/// \"Unknown\" for ids the build did not know about.\n";
    out << "inline const char* to_string(MessageId id) {\n";
    out << "    switch (id) {\n";
    for (const auto& [name, id] : entries) {
        out << "    case MessageId::" << name << ": return \"" << name << "\";\n";
    }
    out << "    default: return \"Unknown\";\n";
    out << "    }\n";
    out << "}\n\n";
    out << "} // namespace esphome::api\n";

    std::fprintf(stderr, "gen_message_ids: emitted %zu ids (max %u)\n", entries.size(), max_id);
    return 0;
}
